---
- name: Stop and disable systemd service
  systemd:
    name: "{{ container }}.service"
    state: stopped
    enabled: no

- name: Remove Nginx config symlink
  file:
    path: "/etc/nginx/sites-enabled/{{ domain }}"
    state: absent
  notify: restart nginx

- name: Remove domains from Dehydrated config
  lineinfile: 
    path: /etc/dehydrated/domains.txt
    regexp: "^{{ domain }} www.{{ domain }}$"
    state: absent