---
- name: restart nginx
  systemd:
    state: restarted
    name: nginx

- name: restart mariadb
  systemd:
    state: restarted
    name: mariadb

- name: restart sshd
  systemd:
    state: restarted
    name: sshd