---
- name: Create Letsencrypt directory
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory

- name: Register to Letsencrypt CA
  command: dehydrated --register --accept-terms

- name: Change Dehydrated wellknown directory
  lineinfile:
    path: /etc/dehydrated/config
    regexp: '^WELLKNOWN=*'
    line: 'WELLKNOWN="/var/www/letsencrypt/.well-known/acme-challenge"'
    create: yes

- name: Create Dehydrated cronjob
  cron:
    name: "Renew Letsencrypt certificates"
    minute: "0"
    hour: "7"
    weekday: "5"
    user: root
    job: /usr/bin/dehydrated -c
