---
- name: Install required Python libraries
  apt:
    pkg: python-cryptography
    state: present
    update_cache: yes

- name: Run sshd setup
  import_tasks: sshd.yml
  tags: sshd-setup

- name: Run MariaDB setup
  import_tasks: mariadb.yml
  tags: database-setup

- name: Run Docker setup
  import_tasks: docker.yml
  tags: docker-setup

- name: Run Nginx setup
  import_tasks: nginx.yml
  tags: reverseproxy-setup

- name: Run Letsencrypt configuration
  import_tasks: letsencrypt.yml
  tags: reverseproxy-setup
