---
- name: Install reverse proxy dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx
    - dehydrated

- name: Allow http(s) ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "80"
    - "443"

- name: Remove Nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx