---
- name: Copy temp Nginx configuration (http only)
  template: 
    src: nginx-proxy-http-only.j2
    dest: "/etc/nginx/sites-enabled/{{ domain }}"

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Get Certificates with Dehydrated
  command: dehydrated --cron

- name: Remove temp Nginx config
  file: 
    path: "/etc/nginx/sites-enabled/{{ domain }}"
    state: absent