---
- name: Add domains to domains.txt
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ domain }}"
    create: yes

- set_fact:
    get_new_certificates: false

- name: Check if TLS certificates exist
  stat:
    path: "/var/lib/dehydrated/certs/{{ domain }}/fullchain.pem"
  register: certs_exist_result

- set_fact:
    get_new_certificates: true
  when: certs_exist_result.stat.exists == false

- name: Check if valid TLS certificates are present
  openssl_certificate_info:
    path: "/var/lib/dehydrated/certs/{{ domain }}/fullchain.pem"
    valid_at:
      oneweek: "+7d"
  register: certs_valid_result

- set_fact:
    get_new_certificates: true
  when: (certs_exist_result.stat.exists == false) or (certs_valid_result.valid_at.oneweek == false)

- include_tasks: get-certificates.yml
  when: get_new_certificates == true

- name: Copy Nginx template
  template: 
    src: nginx-proxy.j2
    dest: "/etc/nginx/sites-available/{{ domain }}"

- name: Set Nginx config symlink
  file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted